service: meetups-backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  profile: Skola-test
  region: eu-north-1
  httpApi:
    cors: true
  iam:
    role: arn:aws:iam::836221056428:role/Lambda-Role

plugins:
  - serverless-webpack

package:
  individually: true

functions:
  addUser:
    handler: functions/signup/index.handler
    events:
      - httpApi:
          path: '/api/user/signup'
          method: POST 

  login:
    handler: functions/login/index.handler
    events:
      - httpApi:
          path: '/api/user/login'
          method: POST   

  populateMeetups:
    handler: functions/populateMeetups/index.handler
    events:
      - httpApi:
          path: '/api/populateMeetups'
          method: POST
  
  getMeetups:
    handler: functions/getMeetups/index.handler
    events:
      - httpApi:
          path: '/api/meetups'
          method: GET
  
  bookMeetup:
    handler: functions/bookMeetup/index.handler
    events: 
      - httpApi:
          path: '/api/bookMeetup'
          method: PUT
  
  sendFeedback: 
    handler: functions/sendFeedback/index.handler
    events:
      - httpApi:
          path: '/api/feedBack'
          method: PUT

  deleteBooking:
    handler: functions/deleteBooking/index.handler
    events:
      - httpApi:
          path: '/api/deleteBooking'
          method: DELETE

  getUserInfo: 
    handler: functions/getUserInfo/index.handler
    events:
      - httpApi:
          path: '/api/getUserInfo'
          method: GET

resources:
  Resources:
    meetupsDb:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: meetups-db
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
          - AttributeName: userId
            AttributeType: S   
          - AttributeName: name
            AttributeType: S 
        GlobalSecondaryIndexes:
          - IndexName: GSI1-quiz
            KeySchema:
              - AttributeName: name
                KeyType: HASH
              - AttributeName: userId
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: GSI1-name
            KeySchema:
              - AttributeName: name
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: meetup-users-db
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
        BillingMode: PAY_PER_REQUEST