export const meetups = [
    {
        PK: "MEETUP#1",
        SK: "DETAILS#1",
        name: "Tech Meetup",
        date: "2023-10-31T08:30:00",
        location: "Tech Hub",
        city: "Karlstad",
        description: "A meetup for tech enthusiasts.",
        host: "Tech Society",
        keywords: ["technology", "coding", "web development", "Karlstad"],
        totalTickets: 100,
        feedbacks: [],
        registeredPeople: 0,
    },
    {
        PK: "MEETUP#2",
        SK: "DETAILS#2",
        name: "Music Concert",
        date: "2023-12-01T10:30:00",
        location: "Concert Hall",
        city: "Stockholm",
        description: "Live music performance by top artists.",
        host: "Music Inc.",
        keywords: ["music", "concert", "live performance", "Stockholm"],
        totalTickets: 500,
        feedbacks: [],
        registeredPeople: 0,
    },
    {
        PK: "MEETUP#3",
        SK: "DETAILS#3",
        name: "Startup Pitch",
        date: "2023-12-02T20:30:00",
        location: "Startup Incubator",
        city: "Guthenborg",
        description: "An event for startups to pitch their ideas.",
        host: "Startup Hub",
        keywords: ["startup", "pitch", "entrepreneurship", "Guthenborg"],
        totalTickets: 50,
        feedbacks: [],
        registeredPeople: 0,
      },
      {
        PK: "MEETUP#4",
        SK: "DETAILS#4",
        name: "Art Exhibition",
        date: "2023-12-10T22:30:00",
        location: "Art Gallery",
        city: "Guthenborg",
        description: "An exhibition featuring local artists.",
        host: "Local Art Society",
        keywords: ["art", "exhibition", "painting", "Guthenborg"],
        totalTickets: 200,
        feedbacks: [],
        registeredPeople: 0,
      },
      {
        PK: "MEETUP#5",
        SK: "DETAILS#5",
        name: "Fitness Workshop",
        date: "2023-12-20T19:30:00",
        location: "Fitness Center",
        city: "Stockholm",
        description: "A workshop on fitness and healthy living.",
        host: "FitLife Gym",
        keywords: ["fitness", "workshop", "health", "Stockholm"],
        totalTickets: 40,
        feedbacks: [],
        registeredPeople: 0,
      },
      {
        PK: "MEETUP#6",
        SK: "DETAILS#6",
        name: "Cooking Class",
        date: "2024-01-05T10:30:00",
        location: "Culinary School",
        city: "Uppsala",
        description: "Learn to cook delicious meals from expert chefs.",
        host: "Culinary Institute",
        keywords: ["cooking", "class", "culinary", "Uppsala"],
        totalTickets: 30,
        feedbacks: [],
        registeredPeople: 0,
      },
      {
        PK: "MEETUP#7",
        SK: "DETAILS#7",
        name: "Book Club Meeting",
        date: "2024-01-15T07:30:00",
        location: "Community Center",
        city: "Karlstad",
        description: "Discuss and share your favorite books with fellow readers.",
        host: "Bookworms Club",
        keywords: ["books", "reading", "literature", "Karlstad"],
        totalTickets: 50,
        feedbacks: [],
        registeredPeople: 0,
      },
      {
        PK: "MEETUP#8",
        SK: "DETAILS#8",
        name: "Health and Fitness Expo",
        date: "2024-02-10T21:30:00",
        location: "Expo Center",
        city: "Stockholm",
        description: "Discover the latest in health and fitness.",
        host: "FitLife Expo",
        keywords: ["health", "fitness", "expo", "Stockholm"],
        totalTickets: 150,
        feedbacks: [],
        registeredPeople: 0,
      },
      {
        PK: "MEETUP#9",
        SK: "DETAILS#9",
        name: "Startup Networking Night",
        date: "2024-02-15T15:30:00",
        location: "Tech Lounge",
        city: "Guthenborg",
        description: "Connect with fellow entrepreneurs and investors.",
        host: "Startup Connections",
        keywords: ["startup", "networking", "entrepreneurship", "Guthenborg"],
        totalTickets: 80,
        feedbacks: [],
        registeredPeople: 0,
      },
      {
        PK: "MEETUP#10",
        SK: "DETAILS#10",
        name: "Karlstad Music Festival",
        date: "2024-03-05T08:30:00",
        location: "Outdoor Arena",
        city: "Karlstad",
        description: "A music festival with top artists and local bands.",
        host: "Music Festivals",
        keywords: ["music", "festival", "Karlstad", "live performance"],
        totalTickets: 300,
        feedbacks: [],
        registeredPeople: 0,
      },
      {
        PK: "MEETUP#11",
        SK: "DETAILS#11",
        name: "Culinary Delights Workshop",
        date: "2024-03-20T11:30:00",
        location: "Cooking School",
        city: "Uppsala",
        description: "Learn to cook gourmet meals from renowned chefs.",
        host: "Culinary Creations",
        keywords: ["cooking", "workshop", "culinary", "Uppsala"],
        totalTickets: 40,
        feedbacks: [],
        registeredPeople: 0,
      },
      {
        PK: "MEETUP#12",
        SK: "DETAILS#12",
        name: "Artistic Expression Exhibition",
        date: "2024-04-01T16:30:00",
        location: "Art Gallery",
        city: "Stockholm",
        description: "Explore unique and creative art pieces by local artists.",
        host: "Artistic Expressions",
        keywords: ["art", "exhibition", "Stockholm", "creativity"],
        totalTickets: 100,
        feedbacks: [],
        registeredPeople: 0,
      } 
];